os: linux
arch: amd64
rvm: 2.6.3
env:
  global:
  # FOO
  - secure: YmQUJimdSu7/yIiUe4xtw2AN+0IE0C1G7WdNFuBc3418YdNnu3PLqaT7VvaifGxKqGyoQe1ISyODndlsq7Vru3efXnuLsCw58pRKmmWRTP5SkoNIWBs2DockU467eGCKeOoWDQl+X8tRTjzb9oDp2fTI8/OTOOKYBp5MifWw1xyDczmJU9ICHoNwgXNSezk+hKansE5VaGp1YB8FM0+SrL9pq5GCQMtyyWN1ZwnT4+jnDmTZLkS7T5vkpyJBJa7IG2Jt8M7dpmk5+suvQ96XhXi+xoyBZhtyCAsqHXXZoDGHv1WZ/NsytDRgCVuS7IT1Yf/0D0qQHkkpz5LnMnIQZTQW6lHRf3J64PDhJ9ZbaU1UJrZ79n+7FfZaITqtOz7JHiabVvvOIetm6aK8xLATgt1LYZh78IQicIKbA4QRGidNh+6uJ8Bj+714v9Fgxfqf64naxNnRyhnLo6izBaq7RWrvs052qnns47yH5ChVdX2Kw/OwHJzUsf27HayG5ugNx+sMxinxuO8+G0ebS5mWFHwLR1+C9Rnf78fTRGG2lUeTqACHYtqwD13seR+21MtVN+akXj1+quXA+eK33lLxpU3cU8ySrK0SVWuDjAqUP7BlCnqLiR7eMsxSDGe9B82xDrf4iZ94/gXmQeTnWSCvkCWi1bQWdkwbllYSzMt0grg=
  # BAR
  - secure: X2WnMlDmJRQlgqV5ktJDmC+JWAOlUJI4ECvIsgOKuDmUsFceLzI5J08qRCkRHT9GCapCZn99MlnCCFIy3BMnsWdcDOIfsE+3H8Y0SljIJUDv1gJNNlgyaH2xx9b6m/cxTfAS+yypabAzBTvManYlqgQK2fGE+n4yqgqjGBeIvIhBNCqan4GdZAx7LVDO//rkFvYb6yFpQ5G6tNhtc7ipvg4uzIC/0e61FJkJhshNPk84JSQbHGFN1Dx3ZSljUHyzpByY7LS1U/wRkafwBtQ20AU4rNRGMQ/CYuhBdcZ5MWels2oh0+BDJ/LLfSTinKLlZi9NTONYSQ5gu5rNX4xKdFrF8k7/n+eV1yGSCGXUrBmytI6PqjWf0cuBvSXTCwYRkhCoDXk5YK7zZcvGINHpfWW5fvkUlb3cbUPTEhZYDPF0FSdIzoTlTwsMvYoshtB/HOrkbOjGD+XD2wMB5qdQdXALNKpJF5iheliIKqd9GGVRyUiYrrB0oMgrXJA8AM9uL1Z+B3GGYjNowVeHYWZf2YaOk3uGdoLN7aMO1sZEyUCQMcq6fwvUrAoFgnAd/dN8GmZzoCtpXSEAyvN/pnW/DwrbIg6QCoWff4RjKHJXDrZelJm5j9RWKAbOSLLneLkceBadgpiw3UpNkHEbzz7Y/hIIFCebGHCXXJv+Ui9xj1g=
jobs:
  include:
  - stage: sleep 109
    script: echo $FOO
